// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.aboutweb.qlogix.system.core.crm.entity;

import java.io.Serializable;

privileged aspect Entity_Roo_Serializable {
    
    declare parents: Entity implements Serializable;
    
    private static final long Entity.serialVersionUID = 1L;
    
}
